### ISSUE TITLE
404 On creating an event

### ISSUE THREAD

**Issue by tqg5** [mujuni88/sportsscheduler#48]
The new api call for creating an event is /api/users/groups/groupID/events. So far the app is calling the old api of /api/users/groups/events. Getting this error:

POST http://localhost:3000/api/users/groups/events 404 (Not Found)

**Comment by mujuni88** [comment]
I'm using the new one. Test it out on the heroku app.

**Comment by tqg5** [comment]
Did you push it to dev? @mujuni88

**Comment by mujuni88** [comment]
I'm using the new api i believe. If you look at my code here https://github.com/mujuni88/sportsscheduler/blob/dev/public/modules/events/services/events.client.service.js. You will see. 
I think you are seeing that because you are trying to create an event from the menu instead of creating one while already in a group.

**Comment by tqg5** [comment]
Oh ok. That makes sense @mujuni88
